-- [FINAL CORRECTED SCHEMA v3 for Seoul Region Project]
-- [RESET] Clean start
drop view if exists public.unread_counts_view cascade;
drop table if exists public.gps_requests cascade;
drop table if exists public.attendance_logs cascade;
drop table if exists public.voice_prompts cascade;
drop table if exists public.handovers cascade;
drop table if exists public.chat_messages cascade;
drop table if exists public.chat_user_reading cascade;
drop table if exists public.chat_topic_members cascade;
drop table if exists public.chat_topics cascade;
drop table if exists public.chat_categories cascade;
drop table if exists public.invite_codes cascade;
drop table if exists public.channel_members cascade;
drop table if exists public.channels cascade;
drop table if exists public.profiles cascade;

-- 1. Profiles Table
create table public.profiles (
  id uuid not null primary key, -- Decoupled from auth.users
  username text,
  full_name text,
  avatar_url text,
  website text,
  role text default 'member',
  updated_at timestamp with time zone,
  last_seen_at timestamp with time zone, -- [ADDED] Legacy support
  
  constraint username_length check (char_length(username) >= 3)
);

-- 2. Channels Table
create table public.channels (
  id bigint generated by default as identity primary key,
  name text not null,
  created_by uuid, -- [MODIFIED] Removed FK to avoid circular dependency issues during migration
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Business & verification
  business_number text,
  business_owner_name text,
  is_verified boolean default false,
  
  -- Location & Wifi
  location_lat double precision,
  location_lng double precision,
  address text,
  wifi_ssid text,
  wifi_bssid text,
  auth_mode text default 'location', -- 'location' or 'wifi'
  
  -- Settings
  allow_audio_handover boolean default false,
  allow_audio_chat boolean default false,
  channel_code text -- [ADDED] Legacy support
);



-- 3. Channel Members
create table public.channel_members (
  id bigint generated by default as identity primary key,
  channel_id bigint references public.channels(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  role text default 'staff', -- owner, manager, staff
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(channel_id, user_id)
);

-- 4. Invite Codes
create table public.invite_codes (
  id bigint generated by default as identity primary key,
  channel_id bigint references public.channels(id) on delete cascade not null,
  code text not null,
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone,
  used_count int default 0,
  max_uses int
);

-- 5. Chat Categories
create table public.chat_categories (
  id bigint generated by default as identity primary key, -- [MODIFIED] BigInt for legacy compatibility
  channel_id bigint references public.channels(id) on delete cascade not null,
  name text not null,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Chat Topics
create table public.chat_topics (
  id bigint generated by default as identity primary key, -- [MODIFIED] BigInt for legacy compatibility
  channel_id bigint references public.channels(id) on delete cascade not null,
  name text not null,
  category text, 
  display_order int, -- [ADDED] Legacy support from schema cache error
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_closed boolean default false
);

-- 7. Chat Topic Members
create table public.chat_topic_members (
  id bigint generated by default as identity primary key,
  topic_id bigint references public.chat_topics(id) on delete cascade not null, -- [MODIFIED] BigInt
  user_id uuid references public.profiles(id) on delete cascade not null,
  permission_level text default 'full',
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(topic_id, user_id)
);

-- 8. Chat Messages
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  topic_id bigint references public.chat_topics(id) on delete cascade not null, -- [MODIFIED] BigInt
  user_id uuid references public.profiles(id),
  content text,
  image_url text,
  file_url text, -- inferred
  channel_id bigint, -- [ADDED] Legacy support from schema cache error (nullable)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. Chat User Reading
create table public.chat_user_reading (
  id bigint generated by default as identity primary key,
  topic_id bigint references public.chat_topics(id) on delete cascade not null, -- [MODIFIED] BigInt
  user_id uuid references public.profiles(id) on delete cascade not null,
  last_read_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(topic_id, user_id)
);

-- 10. Unread Counts View
create or replace view public.unread_counts_view as
select 
    cm.topic_id, 
    cm.user_id, 
    count(m.id) as unread_count
from public.chat_topic_members cm
join public.chat_messages m on m.topic_id = cm.topic_id
left join public.chat_user_reading cur on cur.topic_id = cm.topic_id and cur.user_id = cm.user_id
where m.created_at > coalesce(cur.last_read_at, '1970-01-01'::timestamp with time zone)
group by cm.topic_id, cm.user_id;

-- 11. Handovers
create table public.handovers (
  id bigint generated by default as identity primary key,
  channel_id bigint references public.channels(id) on delete cascade not null,
  user_id uuid references public.profiles(id),
  content text not null,
  category text default 'handover', 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- 12. Voice Prompts
create table public.voice_prompts (
  id bigint generated by default as identity primary key,
  keyword text not null,
  user_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 13. Attendance Logs
create table public.attendance_logs (
    id bigint generated by default as identity primary key,
    channel_id bigint references public.channels(id) on delete cascade,
    user_id uuid not null,
    type text, -- 'IN' or 'OUT'
    method text, -- 'GPS', 'WIFI'
    lat double precision,
    lng double precision,
    ip_address text,
    is_verified boolean,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 14. GPS Requests (Ephemeral)
create table public.gps_requests (
    id text primary key,
    user_id uuid not null,
    status text default 'pending',
    lat double precision,
    lng double precision,
    error_message text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- RLS Policies (Simplified: Allow fully authenticated access)
alter table profiles enable row level security;
create policy "Public profiles" on profiles for select using (true);
create policy "Insert own profile" on profiles for insert with check (true);
create policy "Update own profile" on profiles for update using (true);

alter table channels enable row level security;
create policy "Channels viewable" on channels for select using (true);
create policy "Channels insert" on channels for insert with check (auth.role() = 'authenticated');
create policy "Channels update" on channels for update using (auth.role() = 'authenticated');

alter table channel_members enable row level security;
create policy "Members view" on channel_members for select using (auth.role() = 'authenticated');
create policy "Members insert" on channel_members for insert with check (auth.role() = 'authenticated');
create policy "Members update" on channel_members for update using (auth.role() = 'authenticated');
create policy "Members delete" on channel_members for delete using (auth.role() = 'authenticated');

alter table invite_codes enable row level security;
create policy "Invites view" on invite_codes for select using (true); -- needed for joining
create policy "Invites insert" on invite_codes for insert with check (auth.role() = 'authenticated');
create policy "Invites update" on invite_codes for update using (auth.role() = 'authenticated');

alter table chat_categories enable row level security;
create policy "Cats view" on chat_categories for select using (auth.role() = 'authenticated');
create policy "Cats all" on chat_categories for all using (auth.role() = 'authenticated');

alter table chat_topics enable row level security;
create policy "Topics view" on chat_topics for select using (auth.role() = 'authenticated');
create policy "Topics all" on chat_topics for all using (auth.role() = 'authenticated');

alter table chat_topic_members enable row level security;
create policy "TM view" on chat_topic_members for select using (auth.role() = 'authenticated');
create policy "TM all" on chat_topic_members for all using (auth.role() = 'authenticated');

alter table chat_messages enable row level security;
create policy "Messages view" on chat_messages for select using (auth.role() = 'authenticated');
create policy "Messages all" on chat_messages for all using (auth.role() = 'authenticated');

alter table chat_user_reading enable row level security;
create policy "Reading view" on chat_user_reading for select using (auth.role() = 'authenticated');
create policy "Reading all" on chat_user_reading for all using (auth.role() = 'authenticated');

alter table handovers enable row level security;
create policy "Handover view" on handovers for select using (auth.role() = 'authenticated');
create policy "Handover all" on handovers for all using (auth.role() = 'authenticated');

alter table voice_prompts enable row level security;
create policy "Voice view" on voice_prompts for select using (true);
create policy "Voice all" on voice_prompts for all using (true);

alter table attendance_logs enable row level security;
create policy "Att view" on attendance_logs for select using (auth.role() = 'authenticated');
create policy "Att all" on attendance_logs for all using (auth.role() = 'authenticated');

alter table gps_requests enable row level security;
create policy "GPS view" on gps_requests for select using (true);
create policy "GPS all" on gps_requests for all using (true);

-- FORCE SCHEMA CACHE RELOAD
NOTIFY pgrst, 'reload config';
