import os
from db import supabase

def migrate():
    print("Checking database tables...")
    try:
        # Check if profiles has the mock user
        mock_user_id = "00000000-0000-0000-0000-000000000001"
        res = supabase.table("profiles").select("id").eq("id", mock_user_id).execute()
        if not res.data:
            print("Adding mock user to profiles...")
            supabase.table("profiles").insert({
                "id": mock_user_id,
                "full_name": "관리자",
                "username": "admin"
            }).execute()
        
        # Test voice_prompts table
        print("Testing voice_prompts table...")
        supabase.table("voice_prompts").select("id").limit(1).execute()
        print("voice_prompts table is ready.")
        
    except Exception as e:
        print(f"Migration/Check Error: {e}")
        print("\nIMPORTANT: Please ensure you have run the following SQL in your Supabase SQL Editor:\n")
        print("""
-- Create Voice Prompts (Keywords for Whisper)
create table voice_prompts (
  id bigint generated by default as identity primary key,
  keyword text not null,
  user_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table voice_prompts enable row level security;
create policy \"Voice prompts are viewable by everyone\" on voice_prompts for select using (true);
create policy \"Users can insert their own voice prompts\" on voice_prompts for insert with check (true);
create policy \"Users can delete their own voice prompts\" on voice_prompts for delete using (true);
        """)

if __name__ == "__main__":
    migrate()
