-- Phase 9.1: Pro Category Management
CREATE TABLE IF NOT EXISTS chat_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed defaults
INSERT INTO chat_categories (name, display_order) 
VALUES ('공지', 10), ('일반', 5), ('중요', 20), ('개별 업무', 1)
ON CONFLICT (name) DO NOTHING;

-- Ensure chat_topics has category column (already done in Phase 9.0, but for safety)
ALTER TABLE chat_topics ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '일반';

-- Enable Realtime for Categories (Optional but good)
ALTER TABLE chat_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Categories are viewable by everyone" ON chat_categories FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage categories" ON chat_categories FOR ALL USING (true);
