-- Migration: Time-Limited Invite Codes
-- Context: Replace static channel_code with expiring invite codes for better security

-- Create invite_codes table
CREATE TABLE IF NOT EXISTS invite_codes (
    id bigint generated by default as identity primary key,
    channel_id bigint references channels(id) on delete cascade not null,
    code text unique not null,
    created_by uuid references profiles(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    expires_at timestamp with time zone not null,
    used_count int default 0 -- Track how many times the code was used
);

-- Enable RLS
ALTER TABLE invite_codes ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view codes for their channels
DROP POLICY IF EXISTS "View invite codes" ON invite_codes;
CREATE POLICY "View invite codes" ON invite_codes
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM channel_members 
            WHERE channel_id = invite_codes.channel_id 
            AND user_id = auth.uid()
        )
    );

-- Policy: Channel owners/managers can create codes
DROP POLICY IF EXISTS "Create invite codes" ON invite_codes;
CREATE POLICY "Create invite codes" ON invite_codes
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM channel_members 
            WHERE channel_id = invite_codes.channel_id 
            AND user_id = auth.uid()
            AND role IN ('owner', 'manager')
        )
    );

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_invite_codes_code ON invite_codes(code);
CREATE INDEX IF NOT EXISTS idx_invite_codes_expires ON invite_codes(expires_at);

-- Clean up job: Delete expired codes (run this periodically via cron or trigger)
-- For now, we'll handle cleanup in the application code
