-- Migration: Multi-Channel Architecture (Option A)
-- Context: Transforming Single-Tenant to Multi-Tenant (SaaS Style)

BEGIN;

-- 1. Create Channels Table (The "Store" or "Workspace")
CREATE TABLE IF NOT EXISTS channels (
    id bigint generated by default as identity primary key,
    name text not null,
    owner_id uuid references profiles(id), -- The person who pays/owns
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    channel_code text unique -- For inviting staff (e.g. "STORE-1234")
    -- DEFAULT channel specific settings could go here
);

-- 2. Create Channel Memberships (RBAC)
-- Roles: 'owner', 'manager', 'member'
CREATE TABLE IF NOT EXISTS channel_members (
    channel_id bigint references channels(id) on delete cascade,
    user_id uuid references profiles(id) on delete cascade,
    role text default 'member', -- Option A roles
    joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key (channel_id, user_id)
);

-- 3. Initial Data Migration (Legacy Support)
-- Create a "Default Channel" for existing data so nothing is lost.
-- We grab the first user found as temporary owner, or leave null to be claimed.
INSERT INTO channels (name, channel_code)
SELECT '기본 매장', 'DEFAULT-001'
WHERE NOT EXISTS (SELECT 1 FROM channels);

-- Store ID for migration usage
DO $$
DECLARE
    default_ch_id bigint;
BEGIN
    SELECT id INTO default_ch_id FROM channels LIMIT 1;

    -- 4. Add channel_id to existing tables and backfill
    
    -- Table: chat_categories
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='chat_categories' AND column_name='channel_id') THEN
        ALTER TABLE chat_categories ADD COLUMN channel_id bigint references channels(id) on delete cascade;
        UPDATE chat_categories SET channel_id = default_ch_id WHERE channel_id IS NULL;
        ALTER TABLE chat_categories ALTER COLUMN channel_id SET NOT NULL;
    END IF;

    -- Table: chat_topics
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='chat_topics' AND column_name='channel_id') THEN
        ALTER TABLE chat_topics ADD COLUMN channel_id bigint references channels(id) on delete cascade;
        UPDATE chat_topics SET channel_id = default_ch_id WHERE channel_id IS NULL;
        ALTER TABLE chat_topics ALTER COLUMN channel_id SET NOT NULL;
    END IF;

    -- Table: calendar_events
    -- Check if table exists first (it should)
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='calendar_events') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='calendar_events' AND column_name='channel_id') THEN
            ALTER TABLE calendar_events ADD COLUMN channel_id bigint references channels(id) on delete cascade;
            UPDATE calendar_events SET channel_id = default_ch_id WHERE channel_id IS NULL;
            ALTER TABLE calendar_events ALTER COLUMN channel_id SET NOT NULL;
        END IF;
    END IF;

    -- Table: staff_contracts
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='staff_contracts') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='staff_contracts' AND column_name='channel_id') THEN
            ALTER TABLE staff_contracts ADD COLUMN channel_id bigint references channels(id) on delete cascade;
            UPDATE staff_contracts SET channel_id = default_ch_id WHERE channel_id IS NULL;
            ALTER TABLE staff_contracts ALTER COLUMN channel_id SET NOT NULL;
        END IF;
    END IF;
    
    -- Table: voice_prompts (Adding just in case, though user requested separation)
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='voice_prompts') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='voice_prompts' AND column_name='channel_id') THEN
            ALTER TABLE voice_prompts ADD COLUMN channel_id bigint references channels(id) on delete cascade;
            UPDATE voice_prompts SET channel_id = default_ch_id WHERE channel_id IS NULL;
            -- Not forcing NOT NULL here yet as voice prompts might be personal? 
            -- Actually proposal said "Private", so maybe not needed. 
            -- But keeping consistent for now.
             ALTER TABLE voice_prompts ALTER COLUMN channel_id SET NOT NULL;
        END IF;
    END IF;

    -- 5. Migrate Existing Users to Default Channel
    -- Give them 'member' role by default. Owner can promote later.
    INSERT INTO channel_members (channel_id, user_id, role)
    SELECT default_ch_id, id, 'member'
    FROM profiles
    ON CONFLICT (channel_id, user_id) DO NOTHING;

    -- Special Case: Make the user 'ce89c5a4-7f97-4900-a89e-18a713c7968f' (from logs) the owner
    UPDATE channel_members SET role = 'owner' WHERE user_id = 'ce89c5a4-7f97-4900-a89e-18a713c7968f' AND channel_id = default_ch_id;
    UPDATE channels SET owner_id = 'ce89c5a4-7f97-4900-a89e-18a713c7968f' WHERE id = default_ch_id;

END $$;

-- 6. Enable RLS on New Tables
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_members ENABLE ROW LEVEL SECURITY;

-- Policies for Channel Members
DROP POLICY IF EXISTS "View own memberships" ON channel_members;
CREATE POLICY "View own memberships" ON channel_members
    FOR SELECT USING (auth.uid() = user_id);

-- "Users can view channel info if they are members"
DROP POLICY IF EXISTS "View channel info" ON channels;
CREATE POLICY "View channel info" ON channels
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM channel_members WHERE channel_id = channels.id AND user_id = auth.uid())
    );

COMMIT;
