-- Migration: Attendance Verification Fields
-- Adds GPS and Wi-Fi verification support to channels table

ALTER TABLE channels 
ADD COLUMN IF NOT EXISTS latitude double precision,
ADD COLUMN IF NOT EXISTS longitude double precision,
ADD COLUMN IF NOT EXISTS wifi_ssid text,
ADD COLUMN IF NOT EXISTS wifi_bssid text;

-- Create attendance_logs table for persistent records (optional but recommended)
CREATE TABLE IF NOT EXISTS attendance_logs (
    id bigint generated by default as identity primary key,
    channel_id bigint references channels(id) on delete cascade not null,
    user_id uuid references profiles(id) on delete cascade not null,
    type text not null, -- 'IN' or 'OUT'
    method text, -- 'GPS', 'WIFI', 'IP'
    lat double precision,
    lng double precision,
    ip_address text,
    is_verified boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own logs" ON attendance_logs
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can insert own logs" ON attendance_logs
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Owners and managers can view all logs in channel" ON attendance_logs
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM channel_members 
            WHERE channel_id = attendance_logs.channel_id 
            AND user_id = auth.uid() 
            AND role IN ('owner', 'manager')
        )
    );
