-- Create a table for public profiles using Supabase Auth
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  full_name text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create Chat Topics (Rooms)
create table chat_topics (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Pre-populate some topics
insert into chat_topics (name) values ('📢 공지사항'), ('💬 일반 대화'), ('📛 긴급 요청');

alter table chat_topics enable row level security;
create policy "Topics are viewable by everyone" on chat_topics for select using (true);


-- Create Chat Messages
create table chat_messages (
  id bigint generated by default as identity primary key,
  topic_id bigint references chat_topics(id) not null,
  user_id uuid references profiles(id) not null,
  content text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table chat_messages enable row level security;
create policy "Messages are viewable by everyone" on chat_messages for select using (true);
create policy "Authenticated users can insert messages" on chat_messages for insert with check (auth.role() = 'authenticated');

-- Enable Realtime for messages
-- Create Voice Prompts (Keywords for Whisper)
create table voice_prompts (
  id bigint generated by default as identity primary key,
  keyword text not null,
  user_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table voice_prompts enable row level security;
create policy "Voice prompts are viewable by everyone" on voice_prompts for select using (true);
create policy "Users can insert their own voice prompts" on voice_prompts for insert with check (auth.role() = 'authenticated');
create policy "Users can delete their own voice prompts" on voice_prompts for delete using (auth.uid() = user_id);

